# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 07:37
# Updated for Canadian election types
from __future__ import unicode_literals

from django.db import migrations

# Canadian election types definition (inline to avoid import issues in migrations)
CA_ELECTION_TYPES = {
    "federal": {
        "name": "Federal",
        "subtypes": [],
    },
    "provincial": {
        "name": "Provincial",
        "subtypes": [],
    },
    "territorial": {
        "name": "Territorial",
        "subtypes": [],
    },
    "municipal": {
        "name": "Municipal",
        "subtypes": [],
    },
}


def add_initial_election_types(apps, schema_editor):
    ElectionType = apps.get_model("elections", "ElectionType")
    ElectionSubType = apps.get_model("elections", "ElectionSubType")

    for type_name, info in CA_ELECTION_TYPES.items():
        election_type, _ = ElectionType.objects.update_or_create(
            election_type=type_name, defaults={"name": info["name"]}
        )
        for subtype in info.get("subtypes", []):
            ElectionSubType.objects.update_or_create(
                election_type=election_type,
                election_subtype=subtype["election_subtype"],
                defaults={"name": subtype["name"]},
            )


def remove_initial_election_types(apps, schema_editor):
    ElectionType = apps.get_model("elections", "ElectionType")

    ElectionType.objects.filter(
        election_type__in=CA_ELECTION_TYPES.keys()
    ).delete()


class Migration(migrations.Migration):
    dependencies = [("elections", "0002_auto_20161011_0741")]

    operations = [
        migrations.RunPython(
            add_initial_election_types, remove_initial_election_types
        )
    ]
